### ISSUE TITLE
UnicodeError parsing input with md2po

### ISSUE THREAD

**Issue by dingyifei** [mondeja/mdpo#150]
I don't have permission to reopen #125, but I found some additional information that might indicate the underlying issue.

This test Action can run on any repo 
[update_locales.yml.txt](https://github.com/mondeja/mdpo/files/6791300/update_locales.yml.txt)
```
name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MDPO
      run: pip install mdpo
    - name: generate file
      run: touch a.md
    - name: Insert Text
      run: echo "helloworld" >> a.md
    - name: test1
      run: md2po ./a.md
    - name: test2
      run: python -c "import os;print(os.path.exists('a.md'));"
    - name: test3
      run: cat ./a.md | md2po
```
It produces the following result

![图片](https://user-images.githubusercontent.com/15083013/125078329-d085be00-e0f4-11eb-9eb1-ac7f57fa24f7.png)

Looks like the way md2po read files could be causing the issue. 

I modified my script to do something as the following
`< $mdfilepath md2po --md-encoding utf-8 --po-encoding utf-8 -e utf-8 -w $width -q -s -c --po-filepath $pofilepath`
When I ran this script an encoding issue occurred.

I'm trying to use `> filename` to bypass the md2po read file issue, and it works for most of the files except a few ones.

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\md2po-script.py", line 33, in <module>
    sys.exit(load_entry_point('mdpo==0.3.19', 'console_scripts', 'md2po')())
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__main__.py", line 157, in main
    sys.exit(run(args=sys.argv[1:])[1])  # pragma: no cover
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__main__.py", line 148, in run
    pofile = markdown_to_pofile(opts.glob_or_content, **kwargs)
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 624, in markdown_to_pofile
    return Md2Po(
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 510, in extract
    _parse(self.content)
  File "c:\program files\python39\lib\site-packages\mdpo\md2po\__init__.py", line 500, in _parse
    parser.parse(
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc93' in position 1705: surrogates not allowed
```

**Comment by mondeja** [comment]
Thank you for the report @dingyifei, I'm reproducing it [here](https://github.com/mondeja/test-mdpo-125/actions/runs/1015169641) and will try to investigate asap 👍🏼

**Comment by dingyifei** [comment]
![图片](https://user-images.githubusercontent.com/15083013/125081122-3aec2d80-e0f8-11eb-8321-8e6e7922fe08.png)
The newer version changed a bit but is having the same error

**Comment by mondeja** [comment]
The `md2po ./a.md` error has been fixed in [v0.3.56](https://github.com/mondeja/mdpo/releases/tag/v0.3.56) as you can see [here](https://github.com/mondeja/mdpo/runs/3029613275#step:7:1).

**Comment by dingyifei** [comment]
Thank you for improving mdpo!

I think po2md also has a similar issue. Sorry for missing it earlier. It seems like the same issue just in a different place.

The following issue occurred in Action
![图片](https://user-images.githubusercontent.com/15083013/125166236-3b0a2d00-e1cd-11eb-94ad-f0dca560995f.png)

Action yml:
```
name: Update Locales

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MDPO
      run: pip install mdpo
    - name: generate file
      run: touch a.md
    - name: Insert Text
      run: echo "helloworld" >> a.md
    - name: test1
      run: md2po ./a.md
    - name: test2
      run: python -c "import os;print(os.path.exists('a.md'));"
    - name: test3
      run: cat ./a.md | md2po
    - name: test4
      run: cat ./a.md | md2po -s --po-filepath a.po && cat ./a.md | po2md -p a.po
    - name: test5
      run: cat ./a.md | md2po -s --po-filepath a.po && po2md a.md -p a.po
```
